### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by chrishours** [THEREALWWEFAN231/Inertia#1075]
Hey there! An avid user of the Inertia client here, I use the NoteBot so very often, and it's honestly one of the best modules there in my opinion.

I've been looking around trying to find stuff I can add to my Fabric Mod list so I can enhance my capability, Is there any lists of mods that are guaranteed to work with Inertia?
The mod Tweakeroo needs a little bit of a file change in it for it to work but the other mods I've tried don't work. 
The ones that I have found to work are:
Inertia Client 3.1.3 - 1.16.4.jar
litematica-fabric-1.16.4-0.0.0-dev20201103.184101.jar
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2.jar
optifabric-1.8.13.jar
Optifine_1.16.4_HD_U_G5.jar
tweakeroo-fabric-1.16.4-0.10.0-dev.20210209.145902.145902

These are the mods I found that work recently
other fabric mods that include FabricAPI don't work.
Anything I can do here? I would love to be able to add even more to my mod list to create even better songs with notebot!

Edit:
I figured out what was crashing my game, turns out it was optifabric just doesn't like fabric api so I removed it, and voila it opened. I would still love to know which additions you would suggest thought!

**Comment by chrishours** [comment]
I would like to add It keeps going back to Exit Code: 0
if I left any information out that would help let me know and I will gladly provide it!.

**Comment by feliscatusmeows** [comment]
Use the newly renamed "caffine mc" suite of mods for fps.
https://www.curseforge.com/minecraft/mc-mods/sodium
https://www.curseforge.com/minecraft/mc-mods/lithium
https://www.curseforge.com/minecraft/mc-mods/phosphor
Use the baritone fix pinned in #offtopic in discord.
Those are the most important ones because fps is good. 
Then I have other mods. 
Earthcomputer clientcommands
AppleSkin
No Fog
any fabric mapping mod
ok zoomer for zoom
orderly to see mob healthbars
and you can look for more ig

**Comment by chrishours** [comment]
> Use the newly renamed "caffine mc" suite of mods for fps.
> https://www.curseforge.com/minecraft/mc-mods/sodium
> https://www.curseforge.com/minecraft/mc-mods/lithium
> https://www.curseforge.com/minecraft/mc-mods/phosphor
> Use the baritone fix pinned in #offtopic in discord.
> Those are the most important ones because fps is good.
> Then I have other mods.
> Earthcomputer clientcommands
> AppleSkin
> No Fog
> any fabric mapping mod
> ok zoomer for zoom
> orderly to see mob healthbars
> and you can look for more ig

oh, thank you! I recently did find other mods that do work, however, there are some here that helps too! Turns out that optifabric just doesn't like other mods existing, except the ones listed, so If a fix could be found that would be amazing, just for now I'll be looking for alternatives.

**Comment by feliscatusmeows** [comment]
Issue #1078 
> There are ways to get around the optifine issue, we've done it twice and optifine just keeps changing there code for god knows what reason which breaks our fixes.
From @THEREALWWEFAN231 
https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754
Due to optifine being closed source and breaking the new xray fix every 5 seconds you can not expect compatibility with optifine for a while. Optifabric is a clever little thing but it is a _hacky_ workaround classfile patch, rather than the fabric mixin. It is easier to support native open source mods which use mixins, such as sodium.
