### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mspagnola** [THEREALWWEFAN231/Inertia#588]
Inertia Utility Mod version: 3.1
Minecraft version: 1.16.1
Operating system: Win10
Optifine/Other mods: None

What's the issue: Game crash, seemingly due to ESP and Elytra+

**Crash-report(Would be very useful also please format):**
[crash-2020-08-01_11.29.01-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5010862/crash-2020-08-01_11.29.01-client.txt)

**Comment by THEREALWWEFAN231** [comment]
Thank you for reporting, related to #569, please continue to report you crash logs that do not contain this "org.spongepowered.asm.mixin.injection.callback.CancellationException: The call method_23517 is not cancellable."

my only suggestion for now is to not use outline or shader esp option, I think they both cause that to happen, this will be fixed in the next bug fix update.
