### ISSUE TITLE
Inertia breaks movement modules of some other clients

### ISSUE THREAD

**Issue by gggghuuh** [THEREALWWEFAN231/Inertia#708]
**Inertia Utility Mod version:** v3.1.2
**Minecraft version:** 1.12.2
**Operating system:** Manjaro Linux
**Optifine/Other mods:** Optifine + another utility client + inertia

**What's the issue:** Running with the latest version of inertia, it completely breaks the second client's movement modules such as strafe. The clients are able to work together and launch together, but when running with inertia, toggling movement modules of the other client (such as strafe) has no visible effect. 

Simply removing the other client is not a solution; inertia lacks features such as autotrap, etc.

Switching to inertia's speed hacks is also not a solution; to be blunt, they're pretty shit since most of the options do not bypass anticheats such as NCP, and the ones that do are not very fast

I do not expect this issue to be fixed at all judging by the fact that I have not provided any crash logs or errors; there simply are none. However, I am creating this bug report to see if this is a problem that the developer might know how to fix intuitively.

**Crash-report(Would be very useful also please format):** there are no crashes

**Comment by MLGgamingpro** [comment]
Can you please tell us what other utility mod you are using, so i can test it. Also this is probably normal, as mods that do the same thing have "weird" side-effects, i think that this is an issue, might get fixed, if you tell us what client you are using.

**Comment by THEREALWWEFAN231** [comment]
Well you are correct it wont get fixed. We do not suggest inertia with other clients, because inertia edits a lot of the base minecraft code, and when you have 2 things trying to edit the same thing, In most cases it doesn't work, in the speed case, I COULD go out of my way to make it work, but I'm not going to do that as I said, "We do not suggest inertia with other clients". Sometimes its like going left while also trying to go right, it just doesn't really work. But there is "hope", In 3.2 we are planning to add an API, which allows players to make their own modules, commands, etc(if all goes to plan). And maybe when that happens someone will make a crystal pvp mod, that adds auto trap and some other stuff 🤷 .
