### ISSUE TITLE
Suggestion Auto MLG block

### ISSUE THREAD

**Issue by DustRavenN** [THEREALWWEFAN231/Inertia#732]
**Minecraft Version(s)** all

**What is the suggestion**
Auto MLG  block
**Why would this feature be useful**
automatically places blocks under you like scaffolding
but to avoid falling without getting caught in addition to impressing

**Comment by THEREALWWEFAN231** [comment]
Added in the next major update, a Mode in No Fall called Block Clutch, it works *pretty* well due to NCP default config being a bi*** we had to make it a little less "good", but it generally gets the job done, its basically just for showing off, its not as efficient as No Fall Mode Water Bucket, which works like a beauty and you can also show off to your friends.

**Comment by DustRavenN** [comment]
No Fall Mode Water Bucket does not work when falling from too high but it works well otherwise
