### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by mrGRINCH** [THEREALWWEFAN231/Inertia#750]
Inertia Utility Mod version: 3.1.3
Minecraft version: 16.1.3
Operating system: Windows 10 Pro
Optifine/Other mods: Fabric & Sodium

What's the issue: When mining in the Nether if you run into lava and try to remove it by blocking it's source with blocks when you mine the block afterwards the lava is still there. If you try to block the path the lava has spread it spreads even more. 

I tried restarting Inertia and the issue pertained. Restarting Minecraft to default client and blocking the lava up solved the issue.

Crash-report(Would be very useful also please format): Bug doesn't crash game.

Image to show an example of what's happening: https://i.imgur.com/PZOM5Md.png

**Comment by THEREALWWEFAN231** [comment]
I cant this is happening because of Inertia, of course you said it doesn't happen in vanilla, have you tried without Sodium and or Fabric API(if you have it), also the only reason I could see this happening is if the blocks you placed really aren't there, are they still there if you log out and log back in?

**Comment by THEREALWWEFAN231** [comment]
We solved the issue on discord, Reach was creating ghost blocks.
