### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kostureks** [THEREALWWEFAN231/Inertia#877]
**Inertia Utility Mod version:** 
when I want mine with bariston and enter the command #mine diamond_ore, my character searches for the ore, but it stands still and does not move

**Comment by GaiaB0t** [comment]
it's bc you have the sodium mod installed, it breaks baritone

**Comment by Godeps2891** [comment]
1) bruh

2) (1.16)Replacing Baritone with Fabritone guide:
first off just place fabritone, inertia and sodium(im guessing this is why you're doing this) into your mods folder

Open the inertia client .jar with WinRar or something similar
delete the "baritone" folder
delete mixins.baritone.json 
delete mixins.baritone.refmap.json

after you started your game i recommend running the command "@set prefix #" since otherwise you won't be able to chat in IRC and # is baritone's default prefix

**Comment by GaiaB0t** [comment]
also please folllow format next time

**Comment by kostureks** [comment]
already working thanks a lot
