### ISSUE TITLE
remove or allow ViaVersion updates

### ISSUE THREAD

**Issue by ItsYoungDaddy** [THEREALWWEFAN231/Inertia#907]
Minecraft Version all

**What is the suggestion** make the viaversion jar updatable without having to update the entire client or remove viaversion

**Why would this feature be useful** would allow connecting to the latest servers

**Comment by THEREALWWEFAN231** [comment]
No, this isn't really possible, some people have done it before, it is possible sometimes, but sometimes, like right now with 1.12-1.15, it is not possible because there is some Inertia code that needs to be changed, And that was/is done in 3.2.

So basically in 3.2, you will be able to connect to 1.16.4 servers from 1.12.2.
And sometimes you can manually update via version, other times you can't.

**Comment by feliscatusmeows** [comment]
![image](https://user-images.githubusercontent.com/29553771/100569862-34edbe80-3284-11eb-8feb-d22e7718770b.png)
https://github.com/ViaVersion/VIAaaS
